services:
  frontend:
    container_name: frontend_container
    build:
      context: .
      target: development
    environment:
      LISTEN_PORT: 3000
      LISTEN_ADDRESS: '0.0.0.0'
    volumes:
      - ./server:/app/server  # Mount local project folder into the container
      - /app/node_modules  # Prevent overwriting node_modules
      - ./public:/app/public
      - ./server/views:/app/server/views
    tty: true

